version: '3.8'

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gestion-demande-php
    ports:
      - "127.0.0.1:9000:9000"
    restart: unless-stopped
    # On aligne le chemin interne du conteneur sur celui utilis√© par Nginx (/var/www/gestion-demande)
    working_dir: /var/www/gestion-demande
    volumes:
      - .:/var/www/gestion-demande
    environment:
      APP_ENV: prod
      APP_DEBUG: 0
    depends_on:
      - mysql
    networks:
      - backend-network

  mysql:
    image: mysql:8.0
    container_name: gestion-demande-mysql
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: demande_terrain
      MYSQL_USER: gl_user
      MYSQL_PASSWORD: Kaolack@2025
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3307:3306"   # facultatif (debug)
    networks:
      - backend-network

networks:
  backend-network:
    driver: bridge

volumes:
  mysql_data:
