version: '3.8'

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api-platform-php
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - /var/www/gestion-demande:/var/www/html
    ports:
      - "9000:9000"   # ðŸ”¥ OBLIGATOIRE
    environment:
      APP_ENV: prod
      APP_DEBUG: 0
    networks:
      - api-network


  # Optionnel : Base de donnÃ©es MySQL (si nÃ©cessaire)
  # mysql:
  #   image: mysql:8.0
  #   container_name: api-platform-mysql
  #   restart: unless-stopped
  #   environment:
  #     MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
  #     MYSQL_DATABASE: ${MYSQL_DATABASE}
  #     MYSQL_USER: ${MYSQL_USER}
  #     MYSQL_PASSWORD: ${MYSQL_PASSWORD}
  #   volumes:
  #     - mysql_data:/var/lib/mysql
  #   networks:
  #     - api-network
  #   ports:
  #     - "3306:3306"

networks:
  api-network:
    driver: bridge

# volumes:
#   mysql_data:
