controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

when@dev:
  _errors:
    resource: '@FrameworkBundle/Resources/config/routing/errors.xml'
    type: xml
    
api_login:
    path: /api/login
    methods: ['POST']

api_doc:
    path: /api/doc
    controller: api_platform.swagger_ui.action

# config/routes.yaml
# La route pour le refresh token est gérée automatiquement par le bundle dans config/routes/gesdinet_jwt_refresh_token.yaml